# This file was generated by GoReleaser. DO NOT EDIT.
cask "catchbin" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "6d4c4ac64a2be4ecfb553435c6115f23280e9a56fde94afcb7a3b84dd8962c09"
      url "https://github.com/catchbin/cli/releases/download/v#{version}/catchbin_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7e1138397d630407260d49558bee2466d519700eaa361679b5b289b1df19a268"
      url "https://github.com/catchbin/cli/releases/download/v#{version}/catchbin_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "79d54f798ad698a262f87249c2f84002da792c01d4b790f65610972d3357f172"
      url "https://github.com/catchbin/cli/releases/download/v#{version}/catchbin_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2501184a84500fec44b9da42c3785d67250e940479eafb64eccb66f1d24bd262"
      url "https://github.com/catchbin/cli/releases/download/v#{version}/catchbin_#{version}_linux_arm64.tar.gz"
    end
  end

  name "catchbin"
  desc "Forward and replay cloud-captured webhooks to localhost"
  homepage "https://catchbin.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "catchbin"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/catchbin"]
    end
  end

  # No zap stanza required

end
