# This file was generated by GoReleaser. DO NOT EDIT.
cask "catchbin" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "abda2fb735ba8ab5f90414d4c0229632bb43ceeddade788faaf1312c249503f7"
      url "https://github.com/catchbin/cli/releases/download/v#{version}/catchbin_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9c6a48889f2bb37455f2b67024df41301d9e63bf756fa036b288d633171b185f"
      url "https://github.com/catchbin/cli/releases/download/v#{version}/catchbin_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4e8e168af8ec0ca140508cf4ce50ecf313e1c51f0362611258f35c232fad302a"
      url "https://github.com/catchbin/cli/releases/download/v#{version}/catchbin_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6180b001052505060a52c5ecb0baa650e44bb3eb3daa6d7b549a1a25b77a4757"
      url "https://github.com/catchbin/cli/releases/download/v#{version}/catchbin_#{version}_linux_arm64.tar.gz"
    end
  end

  name "catchbin"
  desc "Forward and replay cloud-captured webhooks to localhost"
  homepage "https://catchbin.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "catchbin"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/catchbin"]
    end
  end

  # No zap stanza required

end
