# This file was generated by GoReleaser. DO NOT EDIT.
cask "catchbin" do
  version "0.1.3-rc1"

  on_macos do
    on_intel do
      sha256 "192e7ba9826dfd9cbc3955e6e5f207c0ea7437c9e23b4fe096ea0a697648afc8"
      url "https://github.com/catchbin/cli/releases/download/v#{version}/catchbin_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6bf273180549a05836a6047b560198604267cce36cf77ba1071e4d3bd7ff8418"
      url "https://github.com/catchbin/cli/releases/download/v#{version}/catchbin_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5930b6a07807a75d053f5973f14df4e81ed236ff92fe8712385e705145dd240d"
      url "https://github.com/catchbin/cli/releases/download/v#{version}/catchbin_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3c9dc04b461959f5b5bd7b6063cd744031b90f00e4586fa12d9e6e1287b6296d"
      url "https://github.com/catchbin/cli/releases/download/v#{version}/catchbin_#{version}_linux_arm64.tar.gz"
    end
  end

  name "catchbin"
  desc "Forward and replay cloud-captured webhooks to localhost"
  homepage "https://catchbin.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "catchbin"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/catchbin"]
    end
  end

  # No zap stanza required

end
